# Generated by Django 4.1.3 on 2022-11-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='owner_confirmpass',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='owner',
            name='owner_passward',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_confirmpass',
            field=models.CharField(max_length=1600),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_passward',
            field=models.CharField(max_length=1600),
        ),
    ]
