# Generated by Django 4.1.3 on 2022-11-27 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_owner_owner_confirmpass_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
