# Generated by Django 4.1.3 on 2022-11-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_username', models.CharField(max_length=30)),
                ('user_email', models.EmailField(max_length=100)),
                ('user_city', models.CharField(max_length=50)),
                ('user_passward', models.CharField(max_length=1600)),
                ('user_confirmpass', models.CharField(max_length=1600)),
            ],
        ),
    ]
