# Generated by Django 4.0.5 on 2022-11-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='p_email',
            field=models.EmailField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='c_email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='c_msg',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_confirmpass',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_passward',
            field=models.CharField(max_length=1000),
        ),
    ]
