# Generated by Django 4.0.5 on 2022-11-29 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_owner_owner_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='owner_mobile',
            field=models.CharField(default=0, max_length=15),
        ),
    ]
