# Generated by Django 4.0.5 on 2022-11-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_owner_owner_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='p_img',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
